spring.application.name=WebSocket Proxy
server.address=0.0.0.0

#server.address=172.16.42.2
#server.port=8080

# ??????????? ???? 443 ? ??????????
server.port=8443
# ???? ? ?????? keystorage
server.ssl.key-store=classpath:keystore.p12
# ?????? ??? keystorage
server.ssl.key-store-password=DfdyaIKbJl21FWt7Fq8
# ??? keystorage
server.ssl.keyStoreType=PKCS12
# Alias ?????
server.ssl.keyAlias=tomcat


# ??????? ??????????? ?? ?????? ?????
spring.servlet.multipart.max-file-size=-1
# ??????? ??????????? ?? ?????? ????? ???????
spring.servlet.multipart.max-request-size=-1



# ?? ??????? ?????? ???? ?????? ???? ????
#sudo iptables -A INPUT -p tcp --dport 8080 -j ACCEPT

