spring.application.name=WebSocket Proxy
server.address=0.0.0.0
#server.port=8080

# ??????????? ???? 443 ? ??????????
server.port=8443
# ???? ? ?????? keystorage
server.ssl.key-store=classpath:keystore.p12
# ?????? ??? keystorage
server.ssl.key-store-password=DfdyaIKbJl21FWt7Fq8
# ??? keystorage
server.ssl.keyStoreType=PKCS12
# Alias ?????
server.ssl.keyAlias=tomcat


# ?? ??????? ?????? ???? ?????? ???? ????
#sudo iptables -A INPUT -p tcp --dport 8080 -j ACCEPT

