spring.application.name=WebSocket Proxy
server.address=0.0.0.0

#server.address=192.168.0.19

#server.address=172.16.42.2
#server.port=8080

# ??????????? ???? 443 ? ??????????
server.port=8443
# ???? ? ?????? keystorage
server.ssl.key-store=classpath:keystore.p12
# ?????? ??? keystorage
server.ssl.key-store-password=DfdyaIKbJl21FWt7Fq8
# ??? keystorage
server.ssl.keyStoreType=PKCS12
# Alias ?????
server.ssl.keyAlias=tomcat

server.forward-headers-strategy=framework
# ??????? ??????????? ?? ?????? ?????
spring.servlet.multipart.max-file-size=-1
# ??????? ??????????? ?? ?????? ????? ???????
spring.servlet.multipart.max-request-size=-1



# ?? ??????? ?????? ???? ?????? ???? ????
#sudo iptables -A INPUT -p tcp --dport 8080 -j ACCEPT




#???? ?? ??????????? Spring Boot, ?? ?????? ???????? ?????? ??????? ? ????????? ?????? ???????? ? ????? application.properties

# ????????? ?????? ???????
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,application/javascript,application/json
server.compression.min-response-size=1024

# ????????? ?????? ????????
spring.http.encoding.enabled=true
spring.http.encoding.force=true

#--------------------------------------------------------------------------------------
#?????? ???????? ?????? ??? ???????
BUFFER_SIZE=4096
#??? ??????????? ????? ??????
DEBUG=true
#?????? ?????? ??????? ?? ???????? ??????? ? ????? ??????
COMPRESSMINSIZE=1024





# SQLite configuration

#spring.datasource.username
#spring.datasource.password

# Hibernate properties

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# ??? SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# ????????? ??????????? ? SQLite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:file:./mydb.sqlite
